config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style='display:flex; flex-direction: column; gap: 20px;'>
    <div class='field form-group'>
      <%= form.label :first_name, style: "display: block", class:'form-label' %>
      <%= form.text_field :first_name, class:'form-control', placeholder:'First Name' %>
    </div>

    <div class='field form-group'>
      <%= form.label :last_name, style: "display: block", class:'form-label' %>
      <%= form.text_field :last_name, class:'form-control', placeholder:'Last Name' %>
    </div>

    <div class='field form-group'>
      <%= form.label :email, style: "display: block", class:'form-label' %>
      <%= form.text_field :email, class:'form-control', placeholder:'Email' %>
    </div>

    <div class='field form-group'>
      <%= form.label :phone, style: "display: block", class:'form-label' %>
      <%= form.text_field :phone, class:'form-control', placeholder:'Phone' %>
    </div>

    <div class='field form-group'>
      <%= form.label :twitter, style: "display: block", class:'form-label' %>
      <%= form.text_field :twitter, class:'form-control', placeholder:'Twitter' %>
    </div>

    <div class='field form-group'>
      <%= form.submit class:'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tbody id="<%= dom_id friend %>">
  <tr>
    <th><%= friend.first_name %></th>
    <td><%= friend.last_name %></td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.twitter %></td>
    <td><%= link_to "View", friend %></td>
    <td><%= link_to "Edit", edit_friend_path(friend) %></td>
    <td><%= link_to "Remove", @friend, method: :delete  %></td>
  </tr>
</tbody>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:'btn btn-secondary' %> 
  <%= link_to "Back to friends", friends_path, class:'btn btn-secondary' %>
</div>

app/views/friends/index.html.erb
<h1>Friends</h1>

<div id="friends">
  <table class="table table-dark table-striped-columns">
    <thead>
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Twitter</th>
        <th scope="col">View</th>
        <th scope="col">Edit</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <% @friends.each do |friend| %>
      <%= render friend %>
    <% end %>
  </table>
</div>

<%= link_to "New friend", new_friend_path, class:'btn btn-primary' %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:'btn btn-secondary' %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <br>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:'btn btn-secondary' %> 
  <%= link_to "Destroy this friend", @friend, method: :delete, class:'btn btn-secondary' %>
  <br>
  <br>
  <%= link_to "Back to friends", friends_path, class:'btn btn-primary' %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class='container'>
        <%= link_to 'Friends List', root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <%= link_to 'About', home_about_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'View Friends', friends_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Add Friend', new_friend_path, class:'nav-link' %>
                </li>
            </ul>
        </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>about us</h1>

app/views/home/index.html.erb
<h1>Hello world</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>FriendsList</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>
    <div class='container' style='padding-top: 30px; padding-bottom: 30px;'>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
 </body>
</html>